/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source?: string;
  destination?: string;
  permanent?: boolean;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: "nazar" | "oleh";
  publishedAt?: string;
  updatedAt?: string;
  tags?: Array<string>;
  tldr?: string;
  body?: BlockContent;
  linkedinUrl?: string;
  seo?: Seo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  canonicalUrl?: string;
  noIndex?: boolean;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Redirect
  | Post
  | SanityImageAssetReference
  | Seo
  | BlockContent
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){      _id,  title,  "slug": slug.current,  author,  publishedAt,  updatedAt,  tags,  tldr,  "minutes": round(length(pt::text(body)) / 1100)  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  author: "nazar" | "oleh" | null;
  publishedAt: string | null;
  updatedAt: string | null;
  tags: Array<string> | null;
  tldr: string | null;
  minutes: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  author,  publishedAt,  updatedAt,  tags,  tldr,  "minutes": round(length(pt::text(body)) / 1100),    linkedinUrl,    seo,    body[]{      ...,      _type == "image" => {        ...,        "lqip": asset->metadata.lqip,        "aspectRatio": asset->metadata.dimensions.aspectRatio      }    },    "more": *[_type == "post" && defined(slug.current) && slug.current != ^.slug.current]      | order(publishedAt desc)[0...3]{   _id,  title,  "slug": slug.current,  author,  publishedAt,  updatedAt,  tags,  tldr,  "minutes": round(length(pt::text(body)) / 1100) }  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  author: "nazar" | "oleh" | null;
  publishedAt: string | null;
  updatedAt: string | null;
  tags: Array<string> | null;
  tldr: string | null;
  minutes: number;
  linkedinUrl: string | null;
  seo: Seo | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
        lqip: string | null;
        aspectRatio: number | null;
      }
  > | null;
  more: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    author: "nazar" | "oleh" | null;
    publishedAt: string | null;
    updatedAt: string | null;
    tags: Array<string> | null;
    tldr: string | null;
    minutes: number;
  }>;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{    "slug": slug.current,    publishedAt,    updatedAt  }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
  publishedAt: string | null;
  updatedAt: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc){\n    \n  _id,\n  title,\n  "slug": slug.current,\n  author,\n  publishedAt,\n  updatedAt,\n  tags,\n  tldr,\n  "minutes": round(length(pt::text(body)) / 1100)\n\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  author,\n  publishedAt,\n  updatedAt,\n  tags,\n  tldr,\n  "minutes": round(length(pt::text(body)) / 1100)\n,\n    linkedinUrl,\n    seo,\n    body[]{\n      ...,\n      _type == "image" => {\n        ...,\n        "lqip": asset->metadata.lqip,\n        "aspectRatio": asset->metadata.dimensions.aspectRatio\n      }\n    },\n    "more": *[_type == "post" && defined(slug.current) && slug.current != ^.slug.current]\n      | order(publishedAt desc)[0...3]{ \n  _id,\n  title,\n  "slug": slug.current,\n  author,\n  publishedAt,\n  updatedAt,\n  tags,\n  tldr,\n  "minutes": round(length(pt::text(body)) / 1100)\n }\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]{\n    "slug": slug.current,\n    publishedAt,\n    updatedAt\n  }\n': POST_SLUGS_QUERY_RESULT;
  }
}
