/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source?: string;
  destination?: string;
  permanent?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  client?: string;
  slug?: Slug;
  industry?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  excerpt?: string;
  problem?: BlockContent;
  solution?: BlockContent;
  result?: BlockContent;
  metrics?: Array<
    {
      _key: string;
    } & Metric
  >;
  technologies?: Array<string>;
  links?: Array<
    {
      _key: string;
    } & Cta
  >;
  publishedAt?: string;
  featured?: boolean;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  canonicalUrl?: string;
  noIndex?: boolean;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type FoundersPage = {
  _id: string;
  _type: "foundersPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heroEyebrow?: string;
  heroHeading?: string;
  heroAccent?: string;
  heroSubhead?: string;
  heroCtaLabel?: string;
  heroCtaHelper?: string;
  storyHeading?: string;
  storyAccent?: string;
  storyDifferenceLabel?: string;
  storyDifferenceBig?: string;
  storyDifferenceSub?: string;
  storyStats?: Array<
    {
      _key: string;
    } & Stat
  >;
  storyBody1?: string;
  storyBody2?: string;
  storyOriginLabel?: string;
  storyOriginCaption?: string;
  storyOriginBody?: string;
  believeHeading?: string;
  believeAccent?: string;
  believeItems?: Array<
    {
      _key: string;
    } & InfoCard
  >;
  believeFinaleTitle?: string;
  believeFinaleBody?: string;
  peopleHeading?: string;
  peopleAccent?: string;
  founders?: Array<
    {
      _key: string;
    } & FounderCard
  >;
  peopleFootnote?: string;
  studioHeading?: string;
  studioAccent?: string;
  studioBody?: string;
  studioTeamCaption?: string;
  studioTeamSizeBody?: string;
  finalCtaEyebrow?: string;
  finalCtaHeading?: string;
  finalCtaIntro?: string;
  finalCtaButtonLabel?: string;
  seo?: Seo;
};

export type HowWeWorkPage = {
  _id: string;
  _type: "howWeWorkPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heroEyebrow?: string;
  heroHeading?: string;
  heroAccent?: string;
  heroSubhead?: string;
  heroCtaLabel?: string;
  heroCtaHelper?: string;
  marquee?: Array<string>;
  fearsHeading?: string;
  fearsAccent?: string;
  fearsAnswerLabel?: string;
  fears?: Array<
    {
      _key: string;
    } & FearItem
  >;
  runsHeading?: string;
  runsAccent?: string;
  runsSteps?: Array<
    {
      _key: string;
    } & InfoCard
  >;
  principlesHeading?: string;
  principlesAccent?: string;
  principlesItems?: Array<string>;
  finalCtaEyebrow?: string;
  finalCtaHeading?: string;
  finalCtaIntro?: string;
  finalCtaButtonLabel?: string;
  seo?: Seo;
};

export type ReviewPage = {
  _id: string;
  _type: "reviewPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heroEyebrow?: string;
  heroHeading?: string;
  heroAccent?: string;
  heroSubhead?: string;
  heroCtaLabel?: string;
  heroCtaHelper?: string;
  marquee?: Array<string>;
  problemHeading?: string;
  problemAccent?: string;
  problemBody?: string;
  problemCallout?: string;
  whatHeading?: string;
  whatAccent?: string;
  whatIntro?: string;
  focusLabel?: string;
  focusItems?: Array<string>;
  deliverablesHeading?: string;
  deliverablesAccent?: string;
  deliverablesIntro?: string;
  deliverablesItems?: Array<
    {
      _key: string;
    } & InfoCard
  >;
  deliverablesClosing?: string;
  foundersHeading?: string;
  foundersAccent?: string;
  founders?: Array<
    {
      _key: string;
    } & FounderCard
  >;
  foundersFootnote?: string;
  processHeading?: string;
  processAccent?: string;
  pricingEyebrow?: string;
  pricingPrice?: string;
  pricingPriceSuffix?: string;
  pricingLead?: string;
  pricingNote?: string;
  pricingButtonLabel?: string;
  pricingIncludedLabel?: string;
  pricingIncluded?: Array<string>;
  fitHeading?: string;
  fitChecks?: Array<string>;
  fitNotLabel?: string;
  fitNotBody?: string;
  proofHeading?: string;
  proofAccent?: string;
  faqHeading?: string;
  faqAccent?: string;
  faqItems?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  finalCtaEyebrow?: string;
  finalCtaHeading?: string;
  finalCtaIntro?: string;
  finalCtaButtonLabel?: string;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heroEyebrow?: string;
  heroHeading?: string;
  heroAccent?: string;
  heroSubhead?: string;
  heroPrimaryCtaLabel?: string;
  heroPrimaryCtaLabelShort?: string;
  heroSecondaryCtaLabel?: string;
  heroSecondaryCtaHref?: string;
  marquee?: Array<string>;
  proofHeading?: string;
  proofLinkLabel?: string;
  proofLinkHref?: string;
  whoHeading?: string;
  whoAccent?: string;
  whoIntro?: string;
  whoRows?: Array<
    {
      _key: string;
    } & InfoCard
  >;
  servicesHeading?: string;
  servicesAccent?: string;
  servicesItems?: Array<
    {
      _key: string;
    } & InfoCard
  >;
  servicesFootnote?: string;
  foundersHeading?: string;
  foundersAccent?: string;
  foundersIntro?: string;
  founders?: Array<
    {
      _key: string;
    } & FounderCard
  >;
  foundersFootnote?: string;
  trustHeading?: string;
  trustAccent?: string;
  trustCards?: Array<
    {
      _key: string;
    } & InfoCard
  >;
  reviewCtaHeading?: string;
  reviewCtaAccent?: string;
  reviewCtaIntro?: string;
  reviewCtaButtonLabel?: string;
  finalCtaEyebrow?: string;
  finalCtaHeading?: string;
  finalCtaIntro?: string;
  finalCtaButtonLabel?: string;
  seo?: Seo;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerLinks?: Array<{
    label?: string;
    anchor?: string;
    _type: "navItem";
    _key: string;
  }>;
  headerCtaLabel?: string;
  footerTagline?: string;
  footerCtaLabel?: string;
  footerLinks?: Array<{
    label?: string;
    href?: string;
    _type: "footerLink";
    _key: string;
  }>;
  footerNote?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  description?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  contactEmail?: string;
  contactPhone?: string;
  location?: string;
  socials?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  flowSteps?: Array<
    {
      _key: string;
    } & FlowStep
  >;
  finalCtaCaption?: string;
  finalCtaHelper?: string;
  seo?: Seo;
  analytics?: {
    provider?: "none" | "plausible" | "ga4";
    plausibleDomain?: string;
    gaMeasurementId?: string;
  };
};

export type FounderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "founder";
};

export type FounderCard = {
  _type: "founderCard";
  founder?: FounderReference;
  role?: string;
  bio?: string;
};

export type Founder = {
  _id: string;
  _type: "founder";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: string;
  linkedinUrl?: string;
  order?: number;
};

export type FlowStep = {
  _type: "flowStep";
  tag?: string;
  title?: string;
  description?: string;
};

export type FearItem = {
  _type: "fearItem";
  fear?: string;
  answer?: string;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: string;
};

export type InfoCard = {
  _type: "infoCard";
  title?: string;
  body?: string;
};

export type Stat = {
  _type: "stat";
  value?: string;
  label?: string;
};

export type Cta = {
  _type: "cta";
  label?: string;
  href?: string;
};

export type Metric = {
  _type: "metric";
  value?: string;
  label?: string;
};

export type SocialLink = {
  _type: "socialLink";
  platform?: "linkedin" | "x" | "instagram" | "github" | "youtube" | "email";
  url?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Redirect
  | SanityImageAssetReference
  | CaseStudy
  | Seo
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | FoundersPage
  | HowWeWorkPage
  | ReviewPage
  | HomePage
  | Navigation
  | SiteSettings
  | FounderReference
  | FounderCard
  | Founder
  | FlowStep
  | FearItem
  | FaqItem
  | InfoCard
  | Stat
  | Cta
  | Metric
  | SocialLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    siteName,    description,    contactEmail,    finalCtaCaption,    finalCtaHelper,    flowSteps[]{ _key, tag, title, description },    seo  }
export type SETTINGS_QUERY_RESULT = {
  siteName: string | null;
  description: string | null;
  contactEmail: string | null;
  finalCtaCaption: string | null;
  finalCtaHelper: string | null;
  flowSteps: Array<{
    _key: string;
    tag: string | null;
    title: string | null;
    description: string | null;
  }> | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation"][0]{    headerLinks[]{ _key, label, anchor },    headerCtaLabel,    footerTagline,    footerCtaLabel,    footerLinks[]{ _key, label, href },    footerNote  }
export type NAVIGATION_QUERY_RESULT = {
  headerLinks: Array<{
    _key: string;
    label: string | null;
    anchor: string | null;
  }> | null;
  headerCtaLabel: string | null;
  footerTagline: string | null;
  footerCtaLabel: string | null;
  footerLinks: Array<{
    _key: string;
    label: string | null;
    href: string | null;
  }> | null;
  footerNote: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: FOUNDERS_QUERY
// Query: *[_type == "founder"] | order(order asc){    _id,    name,    linkedinUrl,    photo{      ...,      "lqip": asset->metadata.lqip,      "aspectRatio": asset->metadata.dimensions.aspectRatio    }  }
export type FOUNDERS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  linkedinUrl: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    lqip: string | null;
    aspectRatio: number | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_QUERY
// Query: *[_type == "homePage"][0]{    heroEyebrow, heroHeading, heroAccent, heroSubhead,    heroPrimaryCtaLabel, heroPrimaryCtaLabelShort, heroSecondaryCtaLabel, heroSecondaryCtaHref,    marquee,    proofHeading, proofLinkLabel, proofLinkHref,    whoHeading, whoAccent, whoIntro, whoRows[]{ _key, title, body },    servicesHeading, servicesAccent, servicesItems[]{ _key, title, body }, servicesFootnote,    foundersHeading, foundersAccent, foundersIntro, foundersFootnote,    founders[]{      _key, role, bio,      founder->{ _id, name, linkedinUrl, photo{ ..., "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio } }    },    trustHeading, trustAccent, trustCards[]{ _key, title, body },    reviewCtaHeading, reviewCtaAccent, reviewCtaIntro, reviewCtaButtonLabel,    finalCtaEyebrow, finalCtaHeading, finalCtaIntro, finalCtaButtonLabel  }
export type HOME_QUERY_RESULT = {
  heroEyebrow: string | null;
  heroHeading: string | null;
  heroAccent: string | null;
  heroSubhead: string | null;
  heroPrimaryCtaLabel: string | null;
  heroPrimaryCtaLabelShort: string | null;
  heroSecondaryCtaLabel: string | null;
  heroSecondaryCtaHref: string | null;
  marquee: Array<string> | null;
  proofHeading: string | null;
  proofLinkLabel: string | null;
  proofLinkHref: string | null;
  whoHeading: string | null;
  whoAccent: string | null;
  whoIntro: string | null;
  whoRows: Array<{
    _key: string;
    title: string | null;
    body: string | null;
  }> | null;
  servicesHeading: string | null;
  servicesAccent: string | null;
  servicesItems: Array<{
    _key: string;
    title: string | null;
    body: string | null;
  }> | null;
  servicesFootnote: string | null;
  foundersHeading: string | null;
  foundersAccent: string | null;
  foundersIntro: string | null;
  foundersFootnote: string | null;
  founders: Array<{
    _key: string;
    role: string | null;
    bio: string | null;
    founder: {
      _id: string;
      name: string | null;
      linkedinUrl: string | null;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        lqip: string | null;
        aspectRatio: number | null;
      } | null;
    } | null;
  }> | null;
  trustHeading: string | null;
  trustAccent: string | null;
  trustCards: Array<{
    _key: string;
    title: string | null;
    body: string | null;
  }> | null;
  reviewCtaHeading: string | null;
  reviewCtaAccent: string | null;
  reviewCtaIntro: string | null;
  reviewCtaButtonLabel: string | null;
  finalCtaEyebrow: string | null;
  finalCtaHeading: string | null;
  finalCtaIntro: string | null;
  finalCtaButtonLabel: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_SEO_QUERY
// Query: *[_type == "homePage"][0]{ seo }
export type HOME_SEO_QUERY_RESULT = {
  seo: Seo | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: REVIEW_QUERY
// Query: *[_type == "reviewPage"][0]{    heroEyebrow, heroHeading, heroAccent, heroSubhead, heroCtaLabel, heroCtaHelper, marquee,    problemHeading, problemAccent, problemBody, problemCallout,    whatHeading, whatAccent, whatIntro, focusLabel, focusItems,    deliverablesHeading, deliverablesAccent, deliverablesIntro, deliverablesItems[]{ _key, title, body }, deliverablesClosing,    foundersHeading, foundersAccent, foundersFootnote,    founders[]{      _key, role, bio,      founder->{ _id, name, linkedinUrl, photo{ ..., "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio } }    },    processHeading, processAccent,    pricingEyebrow, pricingPrice, pricingPriceSuffix, pricingLead, pricingNote, pricingButtonLabel, pricingIncludedLabel, pricingIncluded,    fitHeading, fitChecks, fitNotLabel, fitNotBody,    proofHeading, proofAccent,    faqHeading, faqAccent, faqItems[]{ _key, question, answer },    finalCtaEyebrow, finalCtaHeading, finalCtaIntro, finalCtaButtonLabel  }
export type REVIEW_QUERY_RESULT = {
  heroEyebrow: string | null;
  heroHeading: string | null;
  heroAccent: string | null;
  heroSubhead: string | null;
  heroCtaLabel: string | null;
  heroCtaHelper: string | null;
  marquee: Array<string> | null;
  problemHeading: string | null;
  problemAccent: string | null;
  problemBody: string | null;
  problemCallout: string | null;
  whatHeading: string | null;
  whatAccent: string | null;
  whatIntro: string | null;
  focusLabel: string | null;
  focusItems: Array<string> | null;
  deliverablesHeading: string | null;
  deliverablesAccent: string | null;
  deliverablesIntro: string | null;
  deliverablesItems: Array<{
    _key: string;
    title: string | null;
    body: string | null;
  }> | null;
  deliverablesClosing: string | null;
  foundersHeading: string | null;
  foundersAccent: string | null;
  foundersFootnote: string | null;
  founders: Array<{
    _key: string;
    role: string | null;
    bio: string | null;
    founder: {
      _id: string;
      name: string | null;
      linkedinUrl: string | null;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        lqip: string | null;
        aspectRatio: number | null;
      } | null;
    } | null;
  }> | null;
  processHeading: string | null;
  processAccent: string | null;
  pricingEyebrow: string | null;
  pricingPrice: string | null;
  pricingPriceSuffix: string | null;
  pricingLead: string | null;
  pricingNote: string | null;
  pricingButtonLabel: string | null;
  pricingIncludedLabel: string | null;
  pricingIncluded: Array<string> | null;
  fitHeading: string | null;
  fitChecks: Array<string> | null;
  fitNotLabel: string | null;
  fitNotBody: string | null;
  proofHeading: string | null;
  proofAccent: string | null;
  faqHeading: string | null;
  faqAccent: string | null;
  faqItems: Array<{
    _key: string;
    question: string | null;
    answer: string | null;
  }> | null;
  finalCtaEyebrow: string | null;
  finalCtaHeading: string | null;
  finalCtaIntro: string | null;
  finalCtaButtonLabel: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: REVIEW_SEO_QUERY
// Query: *[_type == "reviewPage"][0]{ seo }
export type REVIEW_SEO_QUERY_RESULT = {
  seo: Seo | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOW_WE_WORK_QUERY
// Query: *[_type == "howWeWorkPage"][0]{    heroEyebrow, heroHeading, heroAccent, heroSubhead, heroCtaLabel, heroCtaHelper, marquee,    fearsHeading, fearsAccent, fearsAnswerLabel, fears[]{ _key, fear, answer },    runsHeading, runsAccent, runsSteps[]{ _key, title, body },    principlesHeading, principlesAccent, principlesItems,    finalCtaEyebrow, finalCtaHeading, finalCtaIntro, finalCtaButtonLabel  }
export type HOW_WE_WORK_QUERY_RESULT = {
  heroEyebrow: string | null;
  heroHeading: string | null;
  heroAccent: string | null;
  heroSubhead: string | null;
  heroCtaLabel: string | null;
  heroCtaHelper: string | null;
  marquee: Array<string> | null;
  fearsHeading: string | null;
  fearsAccent: string | null;
  fearsAnswerLabel: string | null;
  fears: Array<{
    _key: string;
    fear: string | null;
    answer: string | null;
  }> | null;
  runsHeading: string | null;
  runsAccent: string | null;
  runsSteps: Array<{
    _key: string;
    title: string | null;
    body: string | null;
  }> | null;
  principlesHeading: string | null;
  principlesAccent: string | null;
  principlesItems: Array<string> | null;
  finalCtaEyebrow: string | null;
  finalCtaHeading: string | null;
  finalCtaIntro: string | null;
  finalCtaButtonLabel: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOW_WE_WORK_SEO_QUERY
// Query: *[_type == "howWeWorkPage"][0]{ seo }
export type HOW_WE_WORK_SEO_QUERY_RESULT = {
  seo: Seo | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: FOUNDERS_PAGE_QUERY
// Query: *[_type == "foundersPage"][0]{    heroEyebrow, heroHeading, heroAccent, heroSubhead, heroCtaLabel, heroCtaHelper,    storyHeading, storyAccent, storyDifferenceLabel, storyDifferenceBig, storyDifferenceSub,    storyStats[]{ _key, value, label }, storyBody1, storyBody2, storyOriginLabel, storyOriginCaption, storyOriginBody,    believeHeading, believeAccent, believeItems[]{ _key, title, body }, believeFinaleTitle, believeFinaleBody,    peopleHeading, peopleAccent, peopleFootnote,    founders[]{      _key, role, bio,      founder->{ _id, name, linkedinUrl, photo{ ..., "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio } }    },    studioHeading, studioAccent, studioBody, studioTeamCaption, studioTeamSizeBody,    finalCtaEyebrow, finalCtaHeading, finalCtaIntro, finalCtaButtonLabel  }
export type FOUNDERS_PAGE_QUERY_RESULT = {
  heroEyebrow: string | null;
  heroHeading: string | null;
  heroAccent: string | null;
  heroSubhead: string | null;
  heroCtaLabel: string | null;
  heroCtaHelper: string | null;
  storyHeading: string | null;
  storyAccent: string | null;
  storyDifferenceLabel: string | null;
  storyDifferenceBig: string | null;
  storyDifferenceSub: string | null;
  storyStats: Array<{
    _key: string;
    value: string | null;
    label: string | null;
  }> | null;
  storyBody1: string | null;
  storyBody2: string | null;
  storyOriginLabel: string | null;
  storyOriginCaption: string | null;
  storyOriginBody: string | null;
  believeHeading: string | null;
  believeAccent: string | null;
  believeItems: Array<{
    _key: string;
    title: string | null;
    body: string | null;
  }> | null;
  believeFinaleTitle: string | null;
  believeFinaleBody: string | null;
  peopleHeading: string | null;
  peopleAccent: string | null;
  peopleFootnote: string | null;
  founders: Array<{
    _key: string;
    role: string | null;
    bio: string | null;
    founder: {
      _id: string;
      name: string | null;
      linkedinUrl: string | null;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        lqip: string | null;
        aspectRatio: number | null;
      } | null;
    } | null;
  }> | null;
  studioHeading: string | null;
  studioAccent: string | null;
  studioBody: string | null;
  studioTeamCaption: string | null;
  studioTeamSizeBody: string | null;
  finalCtaEyebrow: string | null;
  finalCtaHeading: string | null;
  finalCtaIntro: string | null;
  finalCtaButtonLabel: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: FOUNDERS_PAGE_SEO_QUERY
// Query: *[_type == "foundersPage"][0]{ seo }
export type FOUNDERS_PAGE_SEO_QUERY_RESULT = {
  seo: Seo | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: REDIRECTS_QUERY
// Query: *[_type == "redirect" && defined(source) && defined(destination)]{    source,    destination,    permanent  }
export type REDIRECTS_QUERY_RESULT = Array<{
  source: string;
  destination: string;
  permanent: boolean | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0]{\n    siteName,\n    description,\n    contactEmail,\n    finalCtaCaption,\n    finalCtaHelper,\n    flowSteps[]{ _key, tag, title, description },\n    seo\n  }\n': SETTINGS_QUERY_RESULT;
    '\n  *[_type == "navigation"][0]{\n    headerLinks[]{ _key, label, anchor },\n    headerCtaLabel,\n    footerTagline,\n    footerCtaLabel,\n    footerLinks[]{ _key, label, href },\n    footerNote\n  }\n': NAVIGATION_QUERY_RESULT;
    '\n  *[_type == "founder"] | order(order asc){\n    _id,\n    name,\n    linkedinUrl,\n    photo{\n      ...,\n      "lqip": asset->metadata.lqip,\n      "aspectRatio": asset->metadata.dimensions.aspectRatio\n    }\n  }\n': FOUNDERS_QUERY_RESULT;
    '\n  *[_type == "homePage"][0]{\n    heroEyebrow, heroHeading, heroAccent, heroSubhead,\n    heroPrimaryCtaLabel, heroPrimaryCtaLabelShort, heroSecondaryCtaLabel, heroSecondaryCtaHref,\n    marquee,\n    proofHeading, proofLinkLabel, proofLinkHref,\n    whoHeading, whoAccent, whoIntro, whoRows[]{ _key, title, body },\n    servicesHeading, servicesAccent, servicesItems[]{ _key, title, body }, servicesFootnote,\n    foundersHeading, foundersAccent, foundersIntro, foundersFootnote,\n    founders[]{\n      _key, role, bio,\n      founder->{ _id, name, linkedinUrl, photo{ ..., "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio } }\n    },\n    trustHeading, trustAccent, trustCards[]{ _key, title, body },\n    reviewCtaHeading, reviewCtaAccent, reviewCtaIntro, reviewCtaButtonLabel,\n    finalCtaEyebrow, finalCtaHeading, finalCtaIntro, finalCtaButtonLabel\n  }\n': HOME_QUERY_RESULT;
    '\n  *[_type == "homePage"][0]{ seo }\n': HOME_SEO_QUERY_RESULT;
    '\n  *[_type == "reviewPage"][0]{\n    heroEyebrow, heroHeading, heroAccent, heroSubhead, heroCtaLabel, heroCtaHelper, marquee,\n    problemHeading, problemAccent, problemBody, problemCallout,\n    whatHeading, whatAccent, whatIntro, focusLabel, focusItems,\n    deliverablesHeading, deliverablesAccent, deliverablesIntro, deliverablesItems[]{ _key, title, body }, deliverablesClosing,\n    foundersHeading, foundersAccent, foundersFootnote,\n    founders[]{\n      _key, role, bio,\n      founder->{ _id, name, linkedinUrl, photo{ ..., "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio } }\n    },\n    processHeading, processAccent,\n    pricingEyebrow, pricingPrice, pricingPriceSuffix, pricingLead, pricingNote, pricingButtonLabel, pricingIncludedLabel, pricingIncluded,\n    fitHeading, fitChecks, fitNotLabel, fitNotBody,\n    proofHeading, proofAccent,\n    faqHeading, faqAccent, faqItems[]{ _key, question, answer },\n    finalCtaEyebrow, finalCtaHeading, finalCtaIntro, finalCtaButtonLabel\n  }\n': REVIEW_QUERY_RESULT;
    '\n  *[_type == "reviewPage"][0]{ seo }\n': REVIEW_SEO_QUERY_RESULT;
    '\n  *[_type == "howWeWorkPage"][0]{\n    heroEyebrow, heroHeading, heroAccent, heroSubhead, heroCtaLabel, heroCtaHelper, marquee,\n    fearsHeading, fearsAccent, fearsAnswerLabel, fears[]{ _key, fear, answer },\n    runsHeading, runsAccent, runsSteps[]{ _key, title, body },\n    principlesHeading, principlesAccent, principlesItems,\n    finalCtaEyebrow, finalCtaHeading, finalCtaIntro, finalCtaButtonLabel\n  }\n': HOW_WE_WORK_QUERY_RESULT;
    '\n  *[_type == "howWeWorkPage"][0]{ seo }\n': HOW_WE_WORK_SEO_QUERY_RESULT;
    '\n  *[_type == "foundersPage"][0]{\n    heroEyebrow, heroHeading, heroAccent, heroSubhead, heroCtaLabel, heroCtaHelper,\n    storyHeading, storyAccent, storyDifferenceLabel, storyDifferenceBig, storyDifferenceSub,\n    storyStats[]{ _key, value, label }, storyBody1, storyBody2, storyOriginLabel, storyOriginCaption, storyOriginBody,\n    believeHeading, believeAccent, believeItems[]{ _key, title, body }, believeFinaleTitle, believeFinaleBody,\n    peopleHeading, peopleAccent, peopleFootnote,\n    founders[]{\n      _key, role, bio,\n      founder->{ _id, name, linkedinUrl, photo{ ..., "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio } }\n    },\n    studioHeading, studioAccent, studioBody, studioTeamCaption, studioTeamSizeBody,\n    finalCtaEyebrow, finalCtaHeading, finalCtaIntro, finalCtaButtonLabel\n  }\n': FOUNDERS_PAGE_QUERY_RESULT;
    '\n  *[_type == "foundersPage"][0]{ seo }\n': FOUNDERS_PAGE_SEO_QUERY_RESULT;
    '\n  *[_type == "redirect" && defined(source) && defined(destination)]{\n    source,\n    destination,\n    permanent\n  }\n': REDIRECTS_QUERY_RESULT;
  }
}
